/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package openglproject;

import java.awt.Color;

/**
 *
 * @author Gaara-X
 */
public class GLApp extends javax.swing.JFrame {

    float[] cf1 = {0.3f, 0.75f, 1.5f};
    float[] cf2 = {0.3f, 0.55f, 1.5f};
    float[] cf3 = {0.7f, 0.75f, 1.5f};
    float[] cf4 = {0.3f, 0.75f, 1.5f};
    float[] cf5 = {0.56f, 0.75f, 1.5f};
    float[] cf6 = {0.3f, 1.75f, 1.5f};

    /**
     * Creates new form GLApp
     */
    public GLApp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gerarCuboBt = new javax.swing.JButton();
        jColorChooser1 = new javax.swing.JColorChooser();
        gerarParCubosBt = new javax.swing.JButton();
        aplicarCor1Bt = new javax.swing.JButton();
        aplicarCor2Bt = new javax.swing.JButton();
        aplicarCor3Bt = new javax.swing.JButton();
        aplicarCor4Bt = new javax.swing.JButton();
        aplicarCor5Bt = new javax.swing.JButton();
        aplicarCor6Bt = new javax.swing.JButton();
        face1 = new javax.swing.JCheckBox();
        face2 = new javax.swing.JCheckBox();
        face3 = new javax.swing.JCheckBox();
        face4 = new javax.swing.JCheckBox();
        face5 = new javax.swing.JCheckBox();
        face6 = new javax.swing.JCheckBox();
        gerarColisaoCubosBt = new javax.swing.JButton();
        gerarEixosBt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        gerarCuboBt.setText("Gerar Cubo");
        gerarCuboBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gerarCuboBtActionPerformed(evt);
            }
        });

        gerarParCubosBt.setText("Gerar Par de Cubos");
        gerarParCubosBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gerarParCubosBtActionPerformed(evt);
            }
        });

        aplicarCor1Bt.setText("Aplicar Cor");
        aplicarCor1Bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aplicarCor1BtActionPerformed(evt);
            }
        });

        aplicarCor2Bt.setText("Aplicar Cor");
        aplicarCor2Bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aplicarCor2BtActionPerformed(evt);
            }
        });

        aplicarCor3Bt.setText("Aplicar Cor");
        aplicarCor3Bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aplicarCor3BtActionPerformed(evt);
            }
        });

        aplicarCor4Bt.setText("Aplicar Cor");
        aplicarCor4Bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aplicarCor4BtActionPerformed(evt);
            }
        });

        aplicarCor5Bt.setText("Aplicar Cor");
        aplicarCor5Bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aplicarCor5BtActionPerformed(evt);
            }
        });

        aplicarCor6Bt.setText("Aplicar Cor");
        aplicarCor6Bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aplicarCor6BtActionPerformed(evt);
            }
        });

        face1.setText("Face 1");
        face1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                face1ActionPerformed(evt);
            }
        });

        face2.setText("Face 2");

        face3.setText("Face 3");

        face4.setText("Face 4");

        face5.setText("Face 5");

        face6.setText("Face 6");

        gerarColisaoCubosBt.setText("Gerar Colisao de Cubos");
        gerarColisaoCubosBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gerarColisaoCubosBtActionPerformed(evt);
            }
        });

        gerarEixosBt.setText("Gerar Eixos");
        gerarEixosBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gerarEixosBtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jColorChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(gerarCuboBt)
                            .addComponent(face1)
                            .addComponent(face2)
                            .addComponent(face3)
                            .addComponent(face4)
                            .addComponent(face5)
                            .addComponent(face6))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(aplicarCor2Bt)
                                .addComponent(aplicarCor3Bt)
                                .addComponent(aplicarCor4Bt)
                                .addComponent(aplicarCor5Bt)
                                .addComponent(aplicarCor6Bt)
                                .addComponent(aplicarCor1Bt))
                            .addComponent(gerarParCubosBt)))
                    .addComponent(gerarColisaoCubosBt)
                    .addComponent(gerarEixosBt))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(12, Short.MAX_VALUE)
                        .addComponent(jColorChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(aplicarCor1Bt)
                            .addComponent(face1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(aplicarCor2Bt)
                            .addComponent(face2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(aplicarCor3Bt)
                            .addComponent(face3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(aplicarCor4Bt)
                            .addComponent(face4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(aplicarCor5Bt)
                            .addComponent(face5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(aplicarCor6Bt)
                            .addComponent(face6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(gerarEixosBt)
                        .addGap(18, 18, 18)
                        .addComponent(gerarColisaoCubosBt)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(gerarCuboBt)
                            .addComponent(gerarParCubosBt))))
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gerarCuboBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerarCuboBtActionPerformed
        // TODO add your handling code here:
        boolean f1 = face1.isSelected();
        boolean f2 = face2.isSelected();
        boolean f3 = face3.isSelected();
        boolean f4 = face4.isSelected();
        boolean f5 = face5.isSelected();
        boolean f6 = face6.isSelected();

        new ShowCube(f1, f2, f3, f4, f5, f6, cf1, cf2, cf3, cf4, cf5, cf6).executeOneCube();
    }//GEN-LAST:event_gerarCuboBtActionPerformed

    private void aplicarCor1BtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aplicarCor1BtActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        Color c = jColorChooser1.getColor();

        cf1[0] = c.getRed() / 255f;
        cf1[1] = c.getGreen() / 255f;
        cf1[2] = c.getBlue() / 255f;
        
        face1.setForeground(c);
        aplicarCor1Bt.setForeground(c);
    }//GEN-LAST:event_aplicarCor1BtActionPerformed

    private void aplicarCor4BtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aplicarCor4BtActionPerformed
        // TODO add your handling code here:
        Color c = jColorChooser1.getColor();

        cf4[0] = c.getRed() / 255f;
        cf4[1] = c.getGreen() / 255f;
        cf4[2] = c.getBlue() / 255f;
        
        face4.setForeground(c);
        aplicarCor4Bt.setForeground(c);
    }//GEN-LAST:event_aplicarCor4BtActionPerformed

    private void face1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_face1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_face1ActionPerformed

    private void aplicarCor2BtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aplicarCor2BtActionPerformed
        // TODO add your handling code here:
        Color c = jColorChooser1.getColor();

        cf2[0] = c.getRed() / 255f;
        cf2[1] = c.getGreen() / 255f;
        cf2[2] = c.getBlue() / 255f;
        
        face2.setForeground(c);
        aplicarCor2Bt.setForeground(c);
    }//GEN-LAST:event_aplicarCor2BtActionPerformed

    private void aplicarCor3BtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aplicarCor3BtActionPerformed
        // TODO add your handling code here:
        Color c = jColorChooser1.getColor();

        cf3[0] = c.getRed() / 255f;
        cf3[1] = c.getGreen() / 255f;
        cf3[2] = c.getBlue() / 255f;
        
        face3.setForeground(c);
        aplicarCor3Bt.setForeground(c);
    }//GEN-LAST:event_aplicarCor3BtActionPerformed

    private void aplicarCor5BtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aplicarCor5BtActionPerformed
        // TODO add your handling code here:
        Color c = jColorChooser1.getColor();

        cf5[0] = c.getRed() / 255f;
        cf5[1] = c.getGreen() / 255f;
        cf5[2] = c.getBlue() / 255f;
        
        face5.setForeground(c);
        aplicarCor5Bt.setForeground(c);
    }//GEN-LAST:event_aplicarCor5BtActionPerformed

    private void aplicarCor6BtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aplicarCor6BtActionPerformed
        // TODO add your handling code here:
        Color c = jColorChooser1.getColor();

        cf6[0] = c.getRed() / 255f;
        cf6[1] = c.getGreen() / 255f;
        cf6[2] = c.getBlue() / 255f;
        
        face6.setForeground(c);
        aplicarCor6Bt.setForeground(c);
    }//GEN-LAST:event_aplicarCor6BtActionPerformed

    private void gerarParCubosBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerarParCubosBtActionPerformed
        // TODO add your handling code here:
        boolean f1 = face1.isSelected();
        boolean f2 = face2.isSelected();
        boolean f3 = face3.isSelected();
        boolean f4 = face4.isSelected();
        boolean f5 = face5.isSelected();
        boolean f6 = face6.isSelected();
        new ShowCube(f1, f2, f3, f4, f5, f6, cf1, cf2, cf3, cf4, cf5, cf6).executeTwoCubes();
    }//GEN-LAST:event_gerarParCubosBtActionPerformed

    private void gerarColisaoCubosBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerarColisaoCubosBtActionPerformed
        // TODO add your handling code here:
        boolean f1 = face1.isSelected();
        boolean f2 = face2.isSelected();
        boolean f3 = face3.isSelected();
        boolean f4 = face4.isSelected();
        boolean f5 = face5.isSelected();
        boolean f6 = face6.isSelected();
        new ShowCube(f1, f2, f3, f4, f5, f6, cf1, cf2, cf3, cf4, cf5, cf6).executeCubesColision();
    }//GEN-LAST:event_gerarColisaoCubosBtActionPerformed

    private void gerarEixosBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerarEixosBtActionPerformed
        // TODO add your handling code here
        boolean f1 = face1.isSelected();
        boolean f2 = face2.isSelected();
        boolean f3 = face3.isSelected();
        boolean f4 = face4.isSelected();
        boolean f5 = face5.isSelected();
        boolean f6 = face6.isSelected();
        new ShowCube(f1, f2, f3, f4, f5, f6, cf1, cf2, cf3, cf4, cf5, cf6).executeCoordinatesDraw();
    }//GEN-LAST:event_gerarEixosBtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GLApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GLApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GLApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GLApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GLApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aplicarCor1Bt;
    private javax.swing.JButton aplicarCor2Bt;
    private javax.swing.JButton aplicarCor3Bt;
    private javax.swing.JButton aplicarCor4Bt;
    private javax.swing.JButton aplicarCor5Bt;
    private javax.swing.JButton aplicarCor6Bt;
    private javax.swing.JCheckBox face1;
    private javax.swing.JCheckBox face2;
    private javax.swing.JCheckBox face3;
    private javax.swing.JCheckBox face4;
    private javax.swing.JCheckBox face5;
    private javax.swing.JCheckBox face6;
    private javax.swing.JButton gerarColisaoCubosBt;
    private javax.swing.JButton gerarCuboBt;
    private javax.swing.JButton gerarEixosBt;
    private javax.swing.JButton gerarParCubosBt;
    private javax.swing.JColorChooser jColorChooser1;
    // End of variables declaration//GEN-END:variables
}
